name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        working-directory: ./todoapp  # Change if pom.xml is in a different folder
        run: mvn clean install -DskipTests

      - name: Run Tests
        working-directory: ./todoapp  # Change if pom.xml is in a different folder
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add SSH private key to ssh-agent (Optional - if you use SSH keys)
        if: secrets.SSH_PRIVATE_KEY != ''
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          eval "$(ssh-agent -s)"
          ssh-add private_key

      - name: Deploy to server
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Starting deployment..."
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no "$USER_NAME@$HOST" << 'EOF'
            echo "Deploying to server..."
            cd /path/to/deployment/directory || { echo 'Failed to cd'; exit 1; }
            git pull origin main || { echo 'Git pull failed'; exit 1; }
            mvn clean install || { echo 'Maven install failed'; exit 1; }
            java -jar target/your-spring-boot-app.jar & || { echo 'Failed to start application'; exit 1; }
          EOF
