name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        working-directory: ./todoapp  # Change this if pom.xml is in a different folder
        run: mvn clean install -DskipTests

      - name: Run Tests
        working-directory: ./todoapp  # Change this if pom.xml is in a different folder
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to server
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Starting deployment..."
          # Debugging: Print environment variables (DO NOT use this in production)
          echo "USER_NAME=$USER_NAME"
          echo "HOST=$HOST"
          
          # Correct sshpass usage:
          # Ensure that `sshpass` is passing the password to the `ssh` command with `-o` option for SSH
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER_NAME@$HOST << 'EOF'
            cd /path/to/deployment/directory
            git pull origin main
            mvn clean install
            java -jar target/your-spring-boot-app.jar &
          EOF
